export const CROP_TYPES = [
  "Wheat",
  "Barley",
  "Canola",
  "Oat",
  "Sorghum",
  "Corn",
  "Sunflowers",
  "Soybeans",
  "Potatoes",
  "Sugar Beet",
  "Sugarcane",
  "Cotton",
  "Grapes",
  "Olives",
  "Grass",
  "Red Beet",
  "Carrots",
  "Parsnips",
  "Green Beans",
  "Peas",
  "Spinach",
  "Rice",
  "Long Grain Rice",
  "Oilseed Radish",
  "Poplar",
] as const;

export type CropType = (typeof CROP_TYPES)[number];
